name: b1
description: A Server-Driven UI Flutter application that renders screens dynamically from JSON.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  equatable: ^2.0.5
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/video/
    - assets/images/
