import 'package:b1/core/widgets/app_button.dart';
import 'package:b1/core/widgets/app_error_widget.dart';
import 'package:b1/core/widgets/app_loader.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../bloc/home_bloc.dart';
import '../bloc/home_event.dart';
import '../bloc/home_state.dart';
import '../widgets/home_header.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool isLoading = false;
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => HomeBloc()..add(const HomeStarted()),
      child: Scaffold(
        appBar: AppBar(title: const Text('Home')),
        body: BlocBuilder<HomeBloc, HomeState>(
          builder: (context, state) {
            return switch (state.status) {
              HomeStatus.initial ||
              HomeStatus.loading => const AppLoader(message: 'Loading...'),
              HomeStatus.failure => AppErrorWidget(
                message: state.message ?? 'Something went wrong',
                onRetry: () =>
                    context.read<HomeBloc>().add(const HomeStarted()),
              ),
              HomeStatus.success => ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  HomeHeader(title: state.title),
                  const SizedBox(height: 16),
                  Text(
                    'Generated by stackchain',
                    style: Theme.of(context).textTheme.bodyMedium,
                  ),
                  Text(
                    'Generated by stackchain',
                    style: Theme.of(context).textTheme.bodyMedium,
                  ),
                  AppButton(
                    loading: isLoading,
                    label: "Send",
                    expanded: false,
                    onPressed: () async {
                      setState(() {
                        isLoading = true;
                      });

                      await Future.delayed(const Duration(seconds: 10));

                      if (!mounted) return;

                      setState(() {
                        isLoading = false;
                      });
                    },
                  ),
                ],
              ),
            };
          },
        ),
      ),
    );
  }
}
